[build-system]
requires = [
    "scikit-build-core",
    "pxr-arch-dev==25.5.1.*",
    "pxr-tf-dev==25.5.1.*",
    "pxr-gf-dev==25.5.1.*",
    "pxr-vt-dev==25.5.1.*",
    "pxr-boost-dev==25.5.1.*",
]
build-backend = "scikit_build_core.build"

[project]
name = "pxr-ts-dev"
version = "25.5.1"
description = "C++ headers and CMake config for developing with pxr-ts"
readme = "README.md"
requires-python = ">=3.8"
license-files = ["LICENSE.txt", "NOTICE.txt"]
keywords = ["pixar", "open-usd", "dev"]
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows :: Windows 10",
]
dependencies = [
    "pxr-arch-dev==25.5.1.*",
    "pxr-tf-dev==25.5.1.*",
    "pxr-gf-dev==25.5.1.*",
    "pxr-vt-dev==25.5.1.*",
    "pxr-boost-dev==25.5.1.*",
]

[project.urls]
Repository = "https://github.com/untwine/pxr-ts"

[tool.scikit-build]
cmake.version = ">=3.21,<4"
cmake.args = [
    "-DBUILD_TESTS=OFF",
    "-DBUILD_SHARED_LIBS=ON",
    "-DBUILD_PYTHON_BINDINGS=ON",
    "-DCMAKE_INSTALL_LIBDIR=pxr-ts/lib",
    "-DCMAKE_INSTALL_INCLUDEDIR=pxr-ts/include",
    "-DCMAKE_INSTALL_DATAROOTDIR=pxr-ts",
    "-DCMAKE_INSTALL_PYTHON_LIBDIR=pxr-ts/lib/python",
]
sdist.exclude = ["test", ".github"]
